import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ApiError, MarketStore } from '../domain.mjs';

const address = '0x1111111111111111111111111111111111111111';
function makeClock(start = '2026-08-04T12:00:00Z') { let at = Date.parse(start); return { now: () => at, set: (value) => { at = Date.parse(value); } }; }
function skewedSeed(probability) { const base = seed(); base.markets[0].probability = probability; return base; }
async function skewedFixture(probability) { const folder = await mkdtemp(join(tmpdir(), 'verity-')); const clock = makeClock(); const store = await new MarketStore({ file: join(folder, 'db.json'), seed: skewedSeed(probability), clock, challengeWindowSeconds: 60 }).init(); return { store, clock, folder }; }
function seed(close = '2026-08-05T12:00:00Z') { return { markets: [{ id: 'm1', title: 'Market', category: 'Crypto', type: 'deterministic', status: 'trading', outcome: null, preliminaryOutcome: null, probability: .5, volume: 0, liquidity: 10_000, closesAt: close, createdAt: '2026-08-01T00:00:00Z', feeBps: 100, resolutionSpec: { summary: 'x', criteria: ['x'], lockedAt: '2026-08-01T00:00:00Z', version: 'v1' }, sources: [{ name: 'Source', url: 'https://example.test', fetchedAt: null }], settlementStages: [], challenge: null, priceHistory: [.5] }], portfolios: {}, marketRuntime: {}, challenges: [], liquidityPositions: {} }; }
async function fixture(close) { const folder = await mkdtemp(join(tmpdir(), 'verity-')); const clock = makeClock(); const store = await new MarketStore({ file: join(folder, 'db.json'), seed: seed(close), clock, challengeWindowSeconds: 60 }).init(); return { store, clock, folder }; }
async function cleanup(f) { await rm(f.folder, { recursive: true, force: true }); }

test('CPMM buys YES, creates a position, and moves YES price up', async () => { const f = await fixture(); try { const before = (await f.store.getMarket('m1')).probability; const result = await f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 1000 }); assert.ok(result.trade.shares > 0); assert.ok(result.market.probability > before); const portfolio = await f.store.getPortfolio(address); assert.equal(portfolio.positions[0].side, 'YES'); assert.equal(portfolio.history[0].total, 1000); } finally { await cleanup(f); } });
test('NO trade moves YES price down and retains fee', async () => { const f = await fixture(); try { const result = await f.store.trade(address, { marketId: 'm1', side: 'NO', amount: 500 }); assert.ok(result.market.probability < .5); assert.ok(result.trade.fee > 0); } finally { await cleanup(f); } });
test('market closes and can publish preliminary then auto-finalize after window', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); assert.equal((await f.store.getMarket('m1')).status, 'closed'); await f.store.publishPreliminary('m1', { verified: true, outcome: 'YES', evidence: [{ source: 'a' }] }); assert.equal((await f.store.getMarket('m1')).status, 'challenge_window'); f.clock.set('2026-08-04T12:04:00Z'); await f.store.advance(); const market = await f.store.getMarket('m1'); assert.equal(market.status, 'resolved_yes'); assert.equal(market.outcome, 'YES'); } finally { await cleanup(f); } });
test('challenge moves an eligible market to disputed', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); await f.store.publishPreliminary('m1', { verified: true, outcome: 'NO' }); const result = await f.store.challenge(address, { marketId: 'm1', reason: 'conflicting source', stakeAmount: 1000 }); assert.equal(result.market.status, 'disputed'); assert.equal(result.challenge.status, 'under_review'); } finally { await cleanup(f); } });
test('winning claim pays shares and blocks repeat claim', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { await f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 100 }); f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); await f.store.publishPreliminary('m1', { verified: true, outcome: 'YES' }); f.clock.set('2026-08-04T12:04:00Z'); await f.store.advance(); const claim = await f.store.claim(address, { marketId: 'm1' }); assert.ok(claim.amount > 100); await assert.rejects(() => f.store.claim(address, { marketId: 'm1' }), (error) => error.code === 'NOTHING_TO_CLAIM'); } finally { await cleanup(f); } });
test('VOID opens a challenge window before it refunds gross paid cost', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { await f.store.trade(address, { marketId: 'm1', side: 'NO', amount: 125 }); f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); const published = await f.store.publishPreliminary('m1', { verified: true, outcome: 'VOID' }); assert.equal(published.status, 'challenge_window'); await assert.rejects(() => f.store.claim(address, { marketId: 'm1' }), (error) => error.code === 'MARKET_NOT_RESOLVED'); f.clock.set('2026-08-04T12:04:00Z'); await f.store.advance(); assert.equal((await f.store.getMarket('m1')).status, 'void'); const claim = await f.store.claim(address, { marketId: 'm1' }); assert.equal(claim.amount, 125); } finally { await cleanup(f); } });
test('a mistaken VOID can still be challenged inside its window', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); await f.store.publishPreliminary('m1', { verified: true, outcome: 'VOID' }); const result = await f.store.challenge(address, { marketId: 'm1', reason: 'sources were available', stakeAmount: 1000 }); assert.equal(result.market.status, 'disputed'); } finally { await cleanup(f); } });
test('losing side is marked lost rather than left open', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { await f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 100 }); await f.store.trade(address, { marketId: 'm1', side: 'NO', amount: 100 }); f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); await f.store.publishPreliminary('m1', { verified: true, outcome: 'YES' }); f.clock.set('2026-08-04T12:04:00Z'); await f.store.advance(); await f.store.claim(address, { marketId: 'm1' }); const portfolio = await f.store.getPortfolio(address); assert.equal(portfolio.positions.find((p) => p.side === 'YES').status, 'settled'); assert.equal(portfolio.positions.find((p) => p.side === 'NO').status, 'lost'); } finally { await cleanup(f); } });
test('a fill worse than the agreed quote is rejected', async () => { const f = await fixture(); try { const quote = await f.store.quote('m1', 'YES', 500); assert.ok(quote.priceImpact > 0, 'a CPMM quote must carry price impact'); await f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 4000 }); await assert.rejects(() => f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 500, minSharesOut: quote.shares }), (error) => error.code === 'SLIPPAGE_EXCEEDED'); } finally { await cleanup(f); } });
// The old `2 * outReserve / (inReserve + input)` formula happens to be right at 50/50, so
// a 0.5 market cannot catch it. On a skewed book it under-paid by several times over.
for (const probability of [.5, .75, .91, .12]) {
  test(`a small fill prices within a hair of the quoted spot at p=${probability}`, async () => {
    const f = await skewedFixture(probability); try {
      for (const side of ['YES', 'NO']) {
        const spot = side === 'YES' ? probability : 1 - probability;
        const quote = await f.store.quote('m1', side, 10);
        const grossOfFee = quote.avgPrice * (1 - 100 / 10_000);
        assert.ok(Math.abs(grossOfFee - spot) / spot < .01, `${side} at p=${probability}: fill price ${grossOfFee.toFixed(4)} should track spot ${spot}`);
        assert.ok(quote.avgPrice <= 1.02, `a binary share must never quote above $1, got ${quote.avgPrice}`);
      }
    } finally { await cleanup(f); }
  });
}
test('a buy pushes its own side up and the other side down', async () => { const f = await skewedFixture(.75); try { const before = (await f.store.getMarket('m1')).probability; const after = (await f.store.trade(address, { marketId: 'm1', side: 'NO', amount: 2000 })).market.probability; assert.ok(after < before, `buying NO must lower the YES price, went ${before} -> ${after}`); } finally { await cleanup(f); } });
test('an expired quote deadline is refused', async () => { const f = await fixture(); try { await assert.rejects(() => f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 100, deadline: '2026-08-04T11:59:00Z' }), (error) => error.code === 'QUOTE_EXPIRED'); } finally { await cleanup(f); } });
// LP deposits and withdrawals are both priced on equity — collateral minus what the
// traders are already owed. Pricing either one on gross collateral lets an LP take a
// slice of the traders' money, and mixing the two makes the round trip free.
test('an LP withdrawal cannot reach the collateral backing trader payouts', async () => { const f = await fixture(); try { const deposit = await f.store.provideLiquidity(address, { marketId: 'm1', amount: 40_000 }); await f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 10_000 }); await f.store.trade(address, { marketId: 'm1', side: 'NO', amount: 10_000 }); const runtime = f.store.state.marketRuntime.m1.amm; const owed = Math.max(runtime.totalYesShares, runtime.totalNoShares, runtime.refundLiability); const full = await f.store.provideLiquidity(address, { marketId: 'm1', action: 'withdraw', amount: deposit.lpPosition.shares }); assert.ok(full.amount > 0); const after = f.store.state.marketRuntime.m1.amm; assert.ok(after.collateral >= owed - 1e-6, `withdrawal left ${after.collateral} against ${owed} of trader liabilities`); assert.ok(Math.max(after.yesReserve, after.noReserve) <= after.collateral + 1e-6); } finally { await cleanup(f); } });
test('depositing and immediately withdrawing LP shares is not free money', async () => { const f = await fixture(); try { await f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 5_000 }); const deposit = await f.store.provideLiquidity(address, { marketId: 'm1', amount: 1_000 }); const withdrawal = await f.store.provideLiquidity(address, { marketId: 'm1', action: 'withdraw', amount: deposit.lpPosition.shares }); assert.ok(withdrawal.amount <= 1_000 + 1e-6, `round trip returned ${withdrawal.amount} for a 1000 deposit`); assert.ok(withdrawal.amount > 999, `round trip should be close to break-even, got ${withdrawal.amount}`); } finally { await cleanup(f); } });
test('creator receives a machine-readable resolver spec and bad sources are rejected', async () => { const f = await fixture(); try { const sources = [{ name: 'A', url: 'https://a.test' }, { name: 'B', url: 'https://b.test' }, { name: 'C', url: 'https://c.test' }]; const created = await f.store.createMarket(address, { title: 'Will it work?', category: 'Tech', type: 'judgment', closesAt: '2026-09-01T00:00:00Z', initialLiquidity: 1000, resolverContractAddress: '0x2222222222222222222222222222222222222222', interpretationRule: 'Only an official announcement counts', resolutionSpec: { summary: 'yes if', criteria: ['fixed criterion'] }, sources }); assert.equal(created.market.probability, .5); assert.equal(created.market.creator, address); assert.equal(created.market.resolutionSpec.resolver.contract, 'JudgmentResolver'); assert.deepEqual(created.market.resolutionSpec.resolver.args.sources, ['https://a.test', 'https://b.test', 'https://c.test']); await assert.rejects(() => f.store.createMarket(address, { title: 'bad', type: 'structured', closesAt: '2026-09-01T00:00:00Z', initialLiquidity: 1000, resolutionSpec: { summary: 'x', criteria: ['x'] }, sources: [] }), (error) => error.code === 'SOURCES_REQUIRED'); } finally { await cleanup(f); } });
test('a numeric market must carry the comparator and threshold its resolver needs', async () => { const f = await fixture(); try { const sources = [{ name: 'A', url: 'https://a.test', jsonPath: 'data.price', timestampPath: 'data.time', timestampValue: '2026-09-01T00:00:00.000Z' }, { name: 'B', url: 'https://b.test', jsonPath: 'data.price', timestampPath: 'data.time', timestampValue: '2026-09-01T00:00:00.000Z' }, { name: 'C', url: 'https://c.test', jsonPath: 'price', timestampPath: 'time', timestampValue: '2026-09-01T00:00:00.000Z' }]; await assert.rejects(() => f.store.createMarket(address, { title: 'BTC', resolverContractAddress: '0x2222222222222222222222222222222222222222', type: 'deterministic', closesAt: '2026-09-01T00:00:00Z', initialLiquidity: 1000, resolutionSpec: { summary: 'x', criteria: ['x'] }, sources }), (error) => error.code === 'INVALID_COMPARATOR'); const created = await f.store.createMarket(address, { title: 'BTC above 100k', resolverContractAddress: '0x2222222222222222222222222222222222222222', type: 'deterministic', closesAt: '2026-09-01T00:00:00Z', initialLiquidity: 1000, resolutionSpec: { summary: 'x', criteria: ['x'] }, sources, numeric: { comparator: 'GTE', scale: 100, thresholdUnits: 10_000_000, maxSourceSpreadUnits: 5000 } }); assert.equal(created.market.resolutionSpec.resolver.contract, 'NumericResolver'); assert.equal(created.market.resolutionSpec.resolver.args.comparator, 'GTE'); assert.deepEqual(created.market.resolutionSpec.resolver.args.jsonPaths, ['data.price', 'data.price', 'price']); } finally { await cleanup(f); } });
test('a second process picks up committed writes instead of clobbering them', async () => { const f = await fixture(); try { const worker = await new MarketStore({ file: f.store.file, seed: seed(), clock: f.clock, challengeWindowSeconds: 60 }).init(); await f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 750 }); const seen = await worker.getMarket('m1'); assert.ok(seen.volume === 750, `worker should see the API trade, saw volume ${seen.volume}`); await worker.advance(); const after = await f.store.getPortfolio(address); assert.equal(after.positions.length, 1, 'the worker write must not have dropped the trade'); assert.equal((await f.store.getMarket('m1')).volume, 750); } finally { await cleanup(f); } });
test('LP deposit and withdrawal are accounted for', async () => { const f = await fixture(); try { const deposit = await f.store.provideLiquidity(address, { marketId: 'm1', amount: 1000 }); assert.ok(deposit.lpPosition.shares > 0); const withdrawal = await f.store.provideLiquidity(address, { marketId: 'm1', action: 'withdraw', amount: deposit.lpPosition.shares / 2 }); assert.ok(withdrawal.amount > 0); } finally { await cleanup(f); } });
test('low stake exposes stable domain error', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); await f.store.publishPreliminary('m1', { verified: true, outcome: 'YES' }); await assert.rejects(() => f.store.challenge(address, { marketId: 'm1', reason: 'x', stakeAmount: .01 }), (error) => error instanceof ApiError && error.code === 'STAKE_TOO_LOW'); } finally { await cleanup(f); } });
test('API domain refuses caller-selected and replacement preliminary outcomes', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); await assert.rejects(() => f.store.publishPreliminary('m1', { outcome: 'YES' }), (e) => e.code === 'UNVERIFIED_RESOLUTION'); await f.store.publishPreliminary('m1', { verified: true, outcome: 'YES' }); await f.store.challenge(address, { marketId: 'm1', reason: 'wrong snapshot', stakeAmount: 1000 }); await assert.rejects(() => f.store.publishPreliminary('m1', { verified: true, outcome: 'NO' }), (e) => e.code === 'MARKET_NOT_READY'); } finally { await cleanup(f); } });
test('sell quote matches fill and reduces only the selected position', async () => { const f = await fixture(); try { await f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 500 }); await f.store.trade(address, { marketId: 'm1', side: 'NO', amount: 300 }); const before = await f.store.getPortfolio(address); const yes = before.positions.find((p) => p.side === 'YES'); const no = before.positions.find((p) => p.side === 'NO'); const shares = yes.shares / 3; const quote = await f.store.quote('m1', 'YES', shares, 'sell'); const fill = await f.store.trade(address, { marketId: 'm1', side: 'YES', action: 'sell', amount: shares, minAmountOut: quote.amountOut * .999 }); assert.ok(Math.abs(fill.trade.total - quote.amountOut) < .001); const after = await f.store.getPortfolio(address); assert.ok(after.positions.find((p) => p.side === 'YES').shares < yes.shares); assert.equal(after.positions.find((p) => p.side === 'NO').shares, no.shares); } finally { await cleanup(f); } });
test('LP can claim its final residual once', async () => { const f = await fixture('2026-08-04T12:01:00Z'); try { await f.store.provideLiquidity(address, { marketId: 'm1', amount: 1000 }); f.clock.set('2026-08-04T12:02:00Z'); await f.store.advance(); await f.store.publishPreliminary('m1', { verified: true, outcome: 'NO' }); f.clock.set('2026-08-04T12:04:00Z'); await f.store.advance(); const claim = await f.store.claimLiquidity(address, { marketId: 'm1' }); assert.ok(claim.amount > 0); await assert.rejects(() => f.store.claimLiquidity(address, { marketId: 'm1' }), (e) => e.code === 'NOTHING_TO_CLAIM'); } finally { await cleanup(f); } });
test('new market remains a non-trading draft until creator binds a verified resolver', async () => { const f = await fixture(); try { const sources=[{name:'A',url:'https://a.test'},{name:'B',url:'https://b.test'},{name:'C',url:'https://c.test'}]; const {market}=await f.store.createMarket(address,{title:'Bound market?',type:'judgment',closesAt:'2026-09-01T00:00:00Z',initialLiquidity:1000,resolutionSpec:{summary:'yes if explicit',criteria:['explicit']},interpretationRule:'Must be explicit',sources}); assert.equal(market.status,'draft'); assert.ok(market.resolutionSpecHash&&market.sourcesHash); await assert.rejects(()=>f.store.trade(address,{marketId:market.id,side:'YES',amount:10}),(e)=>e.code==='MARKET_NOT_TRADING'); const contractAddress='0x2222222222222222222222222222222222222222'; const bound=await f.store.bindResolver(market.id,address,contractAddress,{verified:true,contractAddress}); assert.equal(bound.status,'trading'); assert.equal(bound.resolverContractAddress,contractAddress); } finally { await cleanup(f); } });
test('an on-chain market refuses ledger trades, claims and settlement', async () => { const f = await fixture(); try { const market = f.store.state.markets[0]; market.marketContractAddress = '0x3333333333333333333333333333333333333333'; market.settlement = 'onchain'; for (const call of [() => f.store.trade(address, { marketId: 'm1', side: 'YES', amount: 10 }), () => f.store.provideLiquidity(address, { marketId: 'm1', amount: 10 }), () => f.store.claim(address, { marketId: 'm1' }), () => f.store.publishPreliminary('m1', { verified: true, outcome: 'YES' })]) await assert.rejects(call, (e) => e.code === 'ONCHAIN_MARKET', 'the PredictionMarket contract owns this action'); } finally { await cleanup(f); } });
test('binding a market contract requires the creator, a bound resolver and a verified match', async () => { const f = await fixture(); try { const sources=[{name:'A',url:'https://a.test'},{name:'B',url:'https://b.test'},{name:'C',url:'https://c.test'}]; const { market } = await f.store.createMarket(address, { title: 'On-chain market?', type: 'judgment', closesAt: '2026-09-01T00:00:00Z', initialLiquidity: 10, resolutionSpec: { summary: 'yes if', criteria: ['explicit'] }, interpretationRule: 'Must be explicit', sources }); assert.equal(market.settlement, 'simulation'); const contract = '0x4444444444444444444444444444444444444444'; await assert.rejects(() => f.store.bindMarketContract(market.id, address, contract, { verified: true, contractAddress: contract }), (e) => e.code === 'RESOLVER_NOT_BOUND'); const resolver = '0x2222222222222222222222222222222222222222'; await f.store.bindResolver(market.id, address, resolver, { verified: true, contractAddress: resolver }); await assert.rejects(() => f.store.bindMarketContract(market.id, address, contract, { verified: false }), (e) => e.code === 'UNVERIFIED_MARKET_CONTRACT'); await assert.rejects(() => f.store.bindMarketContract(market.id, '0x9999999999999999999999999999999999999999', contract, { verified: true, contractAddress: contract }), (e) => e.code === 'CREATOR_ONLY'); const bound = await f.store.bindMarketContract(market.id, address, contract, { verified: true, contractAddress: contract, transactionHash: '0xabc' }); assert.equal(bound.settlement, 'onchain'); assert.equal(bound.marketContractAddress, contract); await assert.rejects(() => f.store.bindMarketContract(market.id, address, contract, { verified: true, contractAddress: contract }), (e) => e.code === 'MARKET_CONTRACT_BOUND'); } finally { await cleanup(f); } });
test('seeded reserves never exceed the collateral that backs them', async () => { for (const probability of [.5, .75, .91, .12]) { const f = await skewedFixture(probability); try { const market = await f.store.getMarket('m1'); assert.ok(Math.max(market.poolDepth.yesReserve, market.poolDepth.noReserve) <= market.poolDepth.collateral + 1e-6, `p=${probability} seeds a reserve larger than its collateral`); assert.ok(Math.abs(market.probability - probability) < .001); } finally { await cleanup(f); } } });
